name: "Build and Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # 指定具体版本号
          bundler-cache: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libprotobuf-dev

      - name: Build site
        run: bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            \-\-disable-external=true \
            \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/,/^http:\/\//"

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_site${{ steps.pages.outputs.base_path }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

#触发条件：
#当 main 或 master 分支有 push 事件时触发。
#忽略 .gitignore、README.md、LICENSE 文件的更改。
#支持手动触发（workflow_dispatch）。
#权限：
#
#读取仓库内容。
#写入 GitHub Pages。
#写入 ID 令牌。
#并发控制：
#
#同一时间只允许一个 GitHub Pages 部署在运行。
#如果有新的部署触发，则取消正在进行的部署。
#作业配置：
#
#包含两个作业：build 和 deploy。
#运行环境为 ubuntu-latest。
#步骤 - Build 作业：
#
#检出代码：使用 actions/checkout@v4，无深度限制。
#设置 Pages：使用 actions/configure-pages@v3。
#设置 Ruby：使用 ruby/setup-ruby@v1，Ruby 版本设为 3，启用 Bundler 缓存。
#构建网站：使用 Jekyll 构建网站。
#测试网站：使用 htmlproofer 进行网站测试，禁用外部链接检查。
#上传网站制品：使用 actions/upload-pages-artifact@v1。
#步骤 - Deploy 作业：
#
#部署到 GitHub Pages：需要 build 作业，使用 actions/deploy-pages@v2。